github.com:
    users:
        gabrielag-06:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: gabrielag-06
